#!/bin/bash

if [ ! -d "/Users/hchakoub/goinfre/node" ]; then
    cd "/Users/hchakoub/goinfre/" &&  curl -s https://nodejs.org/dist/v16.17.0/node-v16.17.0-darwin-x64.tar.gz -o node.tar \
    && tar -xf node.tar && mv node-v16.17.0-darwin-x64 node
    export PATH="$PATH:/Users/hchakoub/goinfre/node/bin"
  else
    echo "node folder already exist"
fi
if grep -Fxq "export PATH=\"$PATH:/Users/hchakoub/goinfre/node/bin\"" /Users/hchakoub/.zshrc
then
# code if found
  echo "paht already exported"
else
# code if not found
  echo "exporting path"
  echo "export PATH=\"$PATH:/Users/hchakoub/goinfre/node/bin\"" >> /Users/hchakoub/.zshrc
  #source /Users/hchakoub/.zshrc
fi

